[package]
name = "entities"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = "1.1.2"
anyhow = "1.0.94"
argon2 = "^0.5.3"
tokio = { version = "^1.41.0", features = ["full"] }
