name: L2Shablya

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: cargo install sqlx-cli
    - name: Migrate
      run: sqlx migrate run --database-url "sqlite://local.sqlite?mode=rwc"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
